server:
  port: 8082

spring:
  application:
    name: application-service

  datasource:
    url: jdbc:postgresql://localhost:5432/jobcopilot
    username: admin
    password: 12345678

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: application-group
      auto-offset-reset: earliest